---
- hosts: ds-master
  vars:
    apigee_source_path: ../config
    apigee_dest_path: /tmp/apigee
    apigee_config_file_name: config.txt
  tasks:
  - name: Run Setup with DS Masters profile
    command: "/opt/apigee/apigee-setup/bin/setup.sh -p ds -f {{apigee_dest_path}}/{{apigee_config_file_name}}"
    register: task_result
    until: task_result.rc == 0
    retries: 3
    delay: 1
    sudo: yes
- hosts: ds-slave
  vars:
    apigee_config_file_name: config.txt
    apigee_source_path: ../config
    apigee_dest_path: /tmp/apigee
  tasks:
  - name: Run Setup with DS Slave profile
    command: "/opt/apigee/apigee-setup/bin/setup.sh -p ds -f {{apigee_dest_path}}/{{apigee_config_file_name}}"
    register: task_result
    until: task_result.rc == 0
    retries: 3
    delay: 1
    sudo: yes