- hosts: ms
  vars:
    apigee_source_path: ../config
    apigee_dest_path: /tmp/apigee
    apigee_prod_config_file_name: setup-org-prod.txt
    apigee_test_config_file_name: setup-org-test.txt
  tasks:
  - name: Install provisiong service
    command: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision install"
    sudo: yes
  - name: Run Setup Org on Prod
    command: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision setup-org -f {{apigee_dest_path}}/{{apigee_prod_config_file_name}}"
    ignore_errors: yes
    sudo: yes
  - name: Run Setup Org on Test
    command: "/opt/apigee/apigee-service/bin/apigee-service apigee-provision setup-org -f {{apigee_dest_path}}/{{apigee_test_config_file_name}}"
    ignore_errors: yes
    sudo: yes